name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  runtests:

    runs-on: ubuntu-latest    
    container:
      image: cmscloud/cc7-cvmfs

    steps:
    - run: ls -lrth
    - run: ls /cvmfs/
      if: always()
    - run: ls /
      if: always()
    - run: ls /*
      if: always()
    - run: cat /opt/cms/entrypoint.sh
      if: always()
    - run: /opt/cms/entrypoint.sh ls
      if: always()
    - run: ls /opt/cms/
      if: always()
    - run: scramv1 project CMSSW
      if: always()
    - run: ls /cvmfs/cms.cern.ch/
      if: always()
    - run: ls /opt/cms/cmsset_default.sh
      if: always()
    - uses: actions/checkout@v2

