name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  runtests:

    runs-on: ubuntu-latest    
    container:
      image: azul/zulu-openjdk-alpine:8-jre

    steps:
    - uses: actions/checkout@v2
    - name: cmd1
      run: ls -lrth
    - name: cmd2
      run: ls /cvmfs/
    - name: cmd3
      run: cmsrel CMSSW_10_2_9
    - name: cmd4
      run: scramv1 project CMSSW

