name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  runtests:

    runs-on: ubuntu-latest    
    container:
      image: cmssw/cms:rhel7-latest

    steps:
    - uses: actions/checkout@v2
    - name: cmd1
      run: ls -lrth
    - name: cmd2
      run: ls /cvmfs/
    - name: cmd5
      run: ls /
    - name: cmd6
      run: ls /*
    - name: cmd4
      run: scramv1 project CMSSW
    - name: cmd3
      run: ls /cvmfs/cms.cern.ch/

