name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  runtests:

    runs-on: ubuntu-latest    
    container:
        image: rootproject/root:6.22.00-ubuntu20.04

    steps:
    - run: ls -lrth
      if: always()
    - run: which root
      if: always()
    - uses: actions/checkout@v2
    - run: ls -lrth
      if: always()
